=== rdkcentral/Thunder/Tools/JsonGenerator/schemas/interface.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "jsonrpc": {
      "description": "Version of the json-rpc protocol",
      "type": "string",
      "enum": [
        "2.0"
      ]
    },
    "mode": {
      "description": "Selects code generation mode (e.g. auto)",
      "type": "string",
      "enum": [
        "manual",
        "auto"
      ]
    },
    "info": {
      "description": "Meta information about the interface",
      "type": "object",
      "properties": {
        "title": {
          "description": "Pretty name of the interface",
          "type": "string"
        },
        "class": {
          "description": "Class name of interface",
          "type": "string"
        },
        "description": {
          "description": "Description of the interface",
          "type": "string"
        }
      },
      "required": [
        "class"
      ]
    },
    "definitions": {
      "description": "Global definitions for use in the spec",
      "type": "object"
    },
    "common": {
      "description": "Common definitions for use in the spec",
      "type": "object"
    },
    "include": {
      "description": "Interfaces to include",
      "type": "object"
    },
    "methods": {
      "description": "Definitions of the available procedures in the API. A key equals to the name of a procedure",
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "description": "Definition of an API procedure",
          "type": "object",
          "properties": {
            "summary": {
              "description": "Short summary of what the procedure does",
              "type": "string"
            },
            "description": {
              "description": "Longer description of what the procedure does",
              "type": "string"
            },
            "hint": {
              "description": "Name of the method to use in C++ generated code",
              "type": "string"
            },
            "params": {
              "description": "JSON-Schema of the procedure parameters",
              "type": "object",
              "$ref": "http://json-schema.org/draft-07/schema#"
            },
            "result": {
              "description": "JSON-Schema of the procedure result",
              "type": "object",
              "$ref": "http://json-schema.org/draft-07/schema#"
            },
            "events": {
              "description": "Events related",
              "type": "array",
              "items": {
                "description": "Event",
                "type": "string"
              }
            },
            "errors": {
              "description": "Definition of possible error responses",
              "type": "array",
              "items": {
                "description": "Definition of an error response",
                "type": "object",
                "properties": {
                  "description": {
                    "description": "Description of the failure",
                    "type": "string"
                  },
                  "code": {
                    "description": "Error code",
                    "type": "number"
                  },
                  "message": {
                    "description": "Error message",
                    "type": "string"
                  }
                },
                "required": [
                  "code",
                  "message"
                ]
              }
            }
          },
          "required": [
            "summary"
          ]
        }
      }
    },
    "properties": {
      "description": "Definitions of the available properties in the API. A key equals to the name of a property",
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "description": "Definition of an API property",
          "type": "object",
          "properties": {
            "summary": {
              "description": "Short summary of the property",
              "type": "string"
            },
            "description": {
              "description": "Longer description of the property",
              "type": "string"
            },
            "hint": {
              "description": "Name of the method to use in C++ generated code",
              "type": "string"
            },
            "readonly": {
              "description": "Denotes if the property is read-only",
              "type": "boolean"
            },
            "writeonly": {
              "description": "Denotes if the property is write-only",
              "type": "boolean"
            },
            "index": {
              "description": "Specifies if the property needs an index (child property)",
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Name of the ID"
                },
                "example": {
                  "type": "string",
                  "description": "ID example"
                }
              }
            },
            "params": {
              "description": "JSON-Schema of the property value",
              "type": "object",
              "$ref": "http://json-schema.org/draft-07/schema#"
            },
            "events": {
              "description": "Events related",
              "type": "array",
              "items": {
                "description": "Event",
                "type": "string"
              }
            },
            "errors": {
              "description": "Definition of possible error responses",
              "type": "array",
              "items": {
                "description": "Definition of an error response",
                "type": "object",
                "properties": {
                  "description": {
                    "description": "Description of the failure",
                    "type": "string"
                  },
                  "code": {
                    "description": "Error code",
                    "type": "number"
                  },
                  "message": {
                    "description": "Error message",
                    "type": "string"
                  }
                },
                "required": [
                  "code",
                  "message"
                ]
              }
            }
          },
          "required": [
            "summary",
            "params"
          ]
        }
      }
    },
    "events": {
      "description": "Definitions of the available events. A key equals to the name of the event",
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "description": "Definition of an event",
          "type": "object",
          "properties": {
            "summary": {
              "description": "Short summary of the event",
              "type": "string"
            },
            "description": {
              "description": "Longer description of the event",
              "type": "string"
            },
            "hint": {
              "description": "Name of the method to use in C++ generated code",
              "type": "string"
            },
            "id": {
              "description": "Specifies if sending the notification is conditional",
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Name of the ID"
                },
                "example": {
                  "type": "string",
                  "description": "ID example"
                }
              }
            },
            "statuslistener": {
              "description": "Determines if the event supports status listening",
              "type": "boolean"
            },
            "params": {
              "description": "JSON-Schema of the event params",
              "type": "object",
              "$ref": "http://json-schema.org/draft-07/schema#"
            }
          },
          "required": [
            "summary"
          ]
        }
      }
    }
  },
  "required": [
    "jsonrpc",
    "info"
  ]
}

=== rdkcentral/Thunder/Source/interfaces/json/BluetoothRemoteControl.json
{
  "$schema": "interface.schema.json",
  "jsonrpc": "2.0",
  "info": {
    "title": "Bluetooth Remote Control API",
    "class": "BluetoothRemoteControl",
    "description": "Bluetooth Remote Control JSON-RPC interface"
  },
  "common": {
    "$ref": "common.json"
  },
  "definitions": {
    "deviceaddress": {
      "description": "Bluetooth address",
      "type": "string",
      "example": "81:6F:B0:91:9B:FE"
    }
  },
  "methods": {
    "assign": {
      "summary": "Assigns a bluetooth device as a remote control unit",
      "params": {
        "type": "object",
        "properties": {
          "address": {
            "$ref": "#/definitions/deviceaddress"
          }
        }
      },
      "result": {
        "$ref": "#/common/results/void"
      },
      "errors": [
        {
          "description": "Bluetooth unavailable",
          "$ref": "#/common/errors/unavailable"
        },
        {
          "description": "Device unknown",
          "$ref": "#/common/errors/unknownkey"
        },
        {
          "description": "Failed to assign the device",
          "$ref": "#/common/errors/general"
        }
      ]
    },
    "revoke": {
      "summary": "Revokes the current remote control assignment",
      "result": {
        "$ref": "#/common/results/void"
      },
      "errors": [
        {
          "description": "Remote not assigned",
          "$ref": "#/common/errors/illegalstate"
        }
      ]
    }
  },
  "properties": {
    "name": {
      "readonly": true,
      "summary": "Unit name",
      "params": {
        "type": "string",
        "description": "Name of the remote control unit",
        "example": "Acme Bluetooth RCU"
      },
      "errors": [
        {
          "$ref": "#/common/errors/illegalstate",
          "description": "No remote has been assigned"
        }
      ]
    },
    "address": {
      "readonly": true,
      "summary": "Bluetooth address of the unit",
      "params": {
        "$ref": "#/definitions/deviceaddress"
      },
      "errors": [
        {
          "$ref": "#/common/errors/illegalstate",
          "description": "No remote has been assigned"
        }
      ]
    },
    "info": {
      "summary": "Unit auxiliary information",
      "readonly": true,
      "params": {
        "type": "object",
        "properties": {
          "model": {
            "type": "string",
            "description": "Unit model name or number",
            "example": "Acme 1500 Plus"
          },
          "serial": {
            "type": "string",
            "description": "Unit serial number",
            "example": "1234567890"
          },
          "firmware": {
            "type": "string",
            "description": "Unit firmware revision",
            "example": "1.0"
          },
          "software": {
            "type": "string",
            "description": "Unit software revision",
            "example": "1.0"
          },
          "manufacturer": {
            "type": "string",
            "description": "Unit manufacturer name",
            "example": "Acme Inc."
          }
        },
        "required": [ ]
      },
      "errors": [
        {
          "$ref": "#/common/errors/illegalstate",
          "description": "No remote has been assigned"
        },
        {
          "$ref": "#/common/errors/general",
          "description": "Failed to retrieve information"
        }
      ]
    },
    "batterylevel": {
      "summary": "Battery level",
      "event": [ "batterylevel" ],
      "readonly": true,
      "params": {
        "type": "number",
        "size": 8,
        "example": 50,
        "description": "Remote control unit's battery level in percentage"
      },
      "errors": [
        {
          "$ref": "#/common/errors/illegalstate",
          "description": "No remote has been assigned"
        },
        {
          "$ref": "#/common/errors/general",
          "description": "Failed to retrieve battery level"
        }
      ]
    },
    "voice": {
      "summary": "Enable or Disable the flow of Voice data fragments from the remote",
      "params": {
        "type": "boolean",
        "description": "enable (true) or disable (false) flow of voice data"
      },
      "errors": [
        {
          "$ref": "#/common/errors/general",
          "description": "Failed to set the voice flow"
        }
      ]
    },
    "audioprofile" : {
      "summary": "Audio profile details",
      "readonly": true,
      "params": {
        "type": "object",
        "properties": {
          "codec": {
            "type": "string",
            "enum" : [ "PCM", "ADPCM" ],
            "example": "ADPCM",
            "description": "Name of the audio codec (*pcm* for uncompressed audio)"
          },
          "channels": {
            "type": "number",
            "size": 8,
            "example": 1,
            "description": "Number of audio channels (1: mono, 2: stereo, etc.)"
          },
          "rate": {
            "type": "number",
            "size": 16,
            "example": 16000,
            "description": "Sample rate (in Hz)"
          },
          "resolution": {
            "type": "number",
            "size": 8,
            "example": 16,
            "description": "Sample resolution (in bits per sample)"
          }
        },
        "required": [
          "codec",
          "channels",
          "rate",
          "resolution"
        ]
      },
      "errors": [
        {
          "$ref": "#/common/errors/illegalstate",
          "description": "No remote has been assigned"
        },
        {
          "$ref": "#/common/errors/unknownkey",
          "description": "The supplied audio profile is unknown"
        }
      ]
    }
  },
  "events": {
    "audiotransmission": {
      "summary": "Notifies about audio data transmission",
      "description": "Register to this event to be notified about audio transmission status",
      "params": {
        "type": "object",
        "properties": {
          "profile": {
            "type": "string",
            "example": "pcm",
            "description": "Type of audio profile, marking start of transmission; empty in case of end of transmission"
          }
        },
        "required": []
      }
    },
    "audioframe": {
      "summary": "Notifies about new audio data available",
      "description": "Register to this event to be notified about audio data",
      "params": {
        "type": "object",
        "properties": {
          "seq": {
            "type": "number",
            "example": 1,
            "description": "Sequence number of the audio frame within current audio transmission"
          },
          "data": {
            "type": "string",
            "example": "yKMHiYh6qJiDspB6S7ihlKOAbivApYEQDCgY0aECCQhpkAqZogP1ECk9GbHGEAkwG8Ax8wArgaAtEMjGQIoYCKKgGCuzBSA/iuWkKEwamLKzOKoCeR2hwQQZKqgBKKqELoGQwQ==",
            "description": "Base64 representation of the binary data of the audio frame; format of the data is specified by the audio profile denoted by the most recent *audiotransmission* notification"
          }
        },
        "required": [
          "data"
        ]
      }
    },
    "batterylevelchange": {
      "summary": "Notifies about battery level changes",
      "description": "Register to this event to be notified about battery level drops",
      "params": {
        "type": "object",
        "properties": {
          "level": {
            "type": "number",
            "size": 8,
            "example": 50,
            "description": "Battery level (in percentage)"
          }
        }
      }
    }
  }
}

=== rdkcentral/Thunder/Source/interfaces/json/DisplayInfo.json
{
  "$schema": "interface.schema.json",
  "jsonrpc": "2.0",
  "info": {
    "title": "Display Info API",
    "class": "DisplayInfo",
    "description": "DisplayInfo JSON-RPC interface"
  },
  "properties": {
    "displayinfo": {
      "summary": "Display general information",
      "readonly": true,
      "params": {
        "type": "object",
        "properties": {
          "totalgpuram": {
            "description": "Total GPU DRAM memory (in bytes)",
            "example": 381681664,
            "type": "number",
            "size": 64
          },
          "freegpuram": {
            "description": "Free GPU DRAM memory (in bytes)",
            "example": 358612992,
            "type": "number",
            "size": 64
          },
          "audiopassthrough": {
            "description": "Audio Pass through is support for this device",
            "type": "boolean",
            "example": false
          },
          "connected": {
            "description": "HDMI display connection status",
            "type": "boolean",
            "example": true
          },
          "width": {
            "description": "Width of the connected HDMI display",
            "type": "number",
            "size": 32,
            "example": 1280
          },
          "height": {
            "description": "Height of the connected HDMI display",
            "type": "number",
            "size": 32,
            "example": 720
          },
          "hdcpprotection": {
            "description": "HDCP Protection",
            "type": "string",
            "enum": [ "Unencrypted", "HDCP1x", "HDCP2x"],
            "example": "HDCP1x"
          },
          "hdrtype": {
            "description": "HDR Type used",
            "type": "string",
            "enum": [ "HDROff", "HDR10", "HDR10Plus", "HDRDolbyVision", "HDRTechnicolor" ],
            "example": "HDROff"
          }
        },
        "required": [
          "totalgpuram",
          "freegpuram",
          "audiopassthrough",
          "connected",
          "width",
          "height",
          "hdcpprotection",
          "hdrtype"
        ]
      }
    }
  },
  "events": {
    "updated": {
      "summary": "Notifies about a change/update in the connection",
      "description": "Register to this event to be notified about any change in the connection"
    }
  }
}

=== rdkcentral/Thunder/Source/interfaces/json/Provisioning.json
{
  "$schema": "interface.schema.json",
  "jsonrpc": "2.0",
  "info": {
    "title": "Provisioning API",
    "class": "Provisioning",
    "description": "Provisioning JSON-RPC interface"
  },
  "common": {
    "$ref": "common.json"
  },
  "properties": {
    "id": {
      "summary": "Provision ID",
      "readonly": true,
      "params": {
        "type": "string",
        "example": "WPE00000uCfrLF45"
      }    
    },
    "state": {
      "summary": "Platform provision state",
      "readonly": true,
      "params": {
        "type": "object",
        "properties": {
          "id": {
            "description": "Provision ID value",
            "type": "string",
            "example": "WPE00000uCfrLF45"
          },
          "status": {
            "description": "Provision status",
            "type": "number",
            "example": 200
          },
          "tokens": {
              "type": "array",
              "description": "List of provisioned systems",
              "items": {
                "type": "string",
                "example": "netflix, playready"
              }
            }
        },
        "required": [
          "id",
          "status",
          "tokens"
        ]
      },
      "errors": [
        {
          "description": "Provisioning Back Office Client not available",
          "$ref": "#/common/errors/unavailable"
        }
      ]
    }
  },
  "methods": {
    "provision": {
      "summary": "Trigers platform provision process",
      "errors": [
        {
          "description": "Provisioning in progress",
          "$ref": "#/common/errors/inprogress"
        },
        {
          "description": "Provisioning Back Office Client not available",
          "$ref": "#/common/errors/unavailable"
        }
      ]
    }
  },
  "events": {
    "provisioningchange": {
      "summary": "Signals a provisioning change",
      "params": {
        "type": "object",
        "properties": {
          "status": {
            "description": "Provision status",
            "type": "number",
            "example": 200
          }
        }
      }
    }
  }
}

=== rdkcentral/Thunder/Source/interfaces/json/FirmwareControl.json
{
  "$schema": "interface.schema.json",
  "jsonrpc": "2.0",
  "info": {
    "title": "Firmware Control API",
    "class": "FirmwareControl",
    "description": "Firmware Control JSON-RPC interface"
  },
  "common": {
    "$ref": "common.json"
  },
  "definitions": {
    "status": {
      "description": "upgrade status",
      "type": "string",
      "enum": [
        "none",
        "upgradestarted",
        "downloadstarted",
        "downloadaborted",
        "downloadcompleted",
        "installinitiated",
        "installnotstarted",
        "installaborted",
        "installstarted",
        "upgradecompleted",
        "upgradecancelled"
      ],
      "example": "completed"
    },
    "error": {
      "description": "reason of error",
      "type": "string",
      "enum": [
        "none",
        "generic",
        "invalidparameters",
        "invalidstate",
        "operationotsupported",
        "incorrecthash",
        "unavailable",
        "timedout",
        "unkown"
      ],
      "example": "operationotsupported"
    },
    "type": {
      "description": "type of the firmware",
      "type": "string",
      "enum": [
        "CDL",
        "RCDL"
      ],
      "example": "CDL"
    }
  },
  "properties": {
  "status": {
      "readonly": true,
      "summary": "Current status of a upgrade",
      "events": [
        "upgradeprogress"
      ],
      "params": {
        "$ref": "#/definitions/status"
      }
    }
  },
  "methods": {
    "upgrade": {
      "summary": "Upgrade the device to the given firmware",
      "events": "upgradeprogress",
      "params": {
        "type": "object",
        "properties": {
          "name": {
            "description": "name of the firmware",
            "type": "string",
            "example": "firmware_v.0"
          },
          "location": {
            "description": "location/url of the firmware to be upgraded",
            "type": "string",
            "example": "http://my.site.com/images"
          },
          "type": {
            "$ref": "#/definitions/type"
          },
          "progressinterval": {
            "description": "number of seconds between progress update events (5 seconds, 10 seconds etc). 0 means invoking callback only once to report final upgrade result",
            "type": "number",
            "size": 16,
            "example": "10"
          },
          "hmac": {
            "type": "string",
            "example": "2834e6d07fa4c7778ef7a4e394f38a5c321afbed51d54ad512bd3fffbc7aa5debc",
            "description": "HMAC value of firmare"
          }
        },
        "required": [
          "name"
        ]
      },
      "result": {
        "$ref": "#/common/results/void"
      },
      "errors": [
        {
          "description": "Operation in progress",
          "$ref": "#/common/errors/inprogress"
        },
        {
          "description": "Invalid location given",
          "$ref": "#/common/errors/incorrecturl"
        },
        {
          "description": "Error in download",
          "$ref": "#/common/errors/unavailable"
        },
        {
          "description": "Bad file name given",
          "$ref": "#/common/errors/badrequest"
        },
        {
          "description": "Bad hash value given",
          "$ref": "#/common/errors/unknownkey"
        },
        {
          "description": "Invalid state of device",
          "$ref": "#/common/errors/illegalstate"
        },
        {
          "description": "Incorrect hash given",
          "$ref": "#/common/errors/incorrecthash"
        }
      ]
    }
  },
  "events": {
    "upgradeprogress": {
      "summary": "Notifies progress of upgrade",
      "example": "1.*",
      "params": {
        "type": "object",
        "properties": {
          "status": {
            "$ref": "#/definitions/status"
          },
          "error": {
            "$ref": "#/definitions/error"
          },
          "percentage": {
            "type": "number",
            "descrption": "Percentage of upgrade",
            "size": 8,
            "example": 89
          }
        },
        "required": [
          "status",
          "error",
          "percentage"
        ]
      }
    }
  }
}
